// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpP4-daQ7CXLP9A0SLwfBBZozTS-peke4',
    appId: '1:121846000847:web:021d506e26c2deb15fdbba',
    messagingSenderId: '121846000847',
    projectId: 'formulaire-917f5',
    authDomain: 'formulaire-917f5.firebaseapp.com',
    storageBucket: 'formulaire-917f5.firebasestorage.app',
    measurementId: 'G-90SSLH71BW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHgCDXFAilkqkHCfUzyMfLSO_8ehw55U8',
    appId: '1:121846000847:android:310c3af7730651775fdbba',
    messagingSenderId: '121846000847',
    projectId: 'formulaire-917f5',
    storageBucket: 'formulaire-917f5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzDYOysUxEEzqnVUvn7xdGHdHW6LHqzdA',
    appId: '1:121846000847:ios:18ef3864328ced435fdbba',
    messagingSenderId: '121846000847',
    projectId: 'formulaire-917f5',
    storageBucket: 'formulaire-917f5.firebasestorage.app',
    iosBundleId: 'com.example.flutterFormulaire',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzDYOysUxEEzqnVUvn7xdGHdHW6LHqzdA',
    appId: '1:121846000847:ios:18ef3864328ced435fdbba',
    messagingSenderId: '121846000847',
    projectId: 'formulaire-917f5',
    storageBucket: 'formulaire-917f5.firebasestorage.app',
    iosBundleId: 'com.example.flutterFormulaire',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBpP4-daQ7CXLP9A0SLwfBBZozTS-peke4',
    appId: '1:121846000847:web:0ceb247021c986065fdbba',
    messagingSenderId: '121846000847',
    projectId: 'formulaire-917f5',
    authDomain: 'formulaire-917f5.firebaseapp.com',
    storageBucket: 'formulaire-917f5.firebasestorage.app',
    measurementId: 'G-8XT0WWQ0DZ',
  );
}
